# Generated by Django 5.1.6 on 2025-05-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='Firebase Authentication UID', max_length=128, null=True, unique=True),
        ),
    ]
